# frozen_string_literal: true
source 'https://supermarket.chef.io'

# based on terraform recipe instructions
cookbook 'gpg', git: 'https://github.com/sous-chefs/gpg', ref: '2f682a1406047e99351d184fe18fff035a0c856c'
metadata
